const books = [
  {
    volumeId: 'vol-1',
    title: '1984',
    authors: ['George Orwell'],
    categories: ['Dystopian', 'Political Fiction'],
    description: 'A chilling vision of a totalitarian future where Big Brother watches all.',
    metadata: { year: 1949, isbn: '9780451524935' },
  },
  {
    volumeId: 'vol-2',
    title: 'To Kill a Mockingbird',
    authors: ['Harper Lee'],
    categories: ['Classic', 'Coming-of-Age'],
    description: 'A story of racial injustice and childhood innocence in the Deep South.',
    metadata: { year: 1960, isbn: '9780061120084' },
  },
  {
    volumeId: 'vol-3',
    title: 'The Great Gatsby',
    authors: ['F. Scott Fitzgerald'],
    categories: ['Classic', 'Tragedy'],
    description: 'A critique of the American Dream set in the Roaring Twenties.',
    metadata: { year: 1925, isbn: '9780743273565' },
  },
  {
    volumeId: 'vol-4',
    title: 'Moby-Dick',
    authors: ['Herman Melville'],
    categories: ['Adventure', 'Classic'],
    description: 'Captain Ahab’s obsessive quest for the white whale.',
    metadata: { year: 1851, isbn: '9780142437247' },
  },
  {
    volumeId: 'vol-5',
    title: 'Pride and Prejudice',
    authors: ['Jane Austen'],
    categories: ['Romance', 'Classic'],
    description: 'A witty exploration of manners, marriage, and morality.',
    metadata: { year: 1813, isbn: '9780141439518' },
  },
  {
    volumeId: 'vol-6',
    title: 'Brave New World',
    authors: ['Aldous Huxley'],
    categories: ['Dystopian', 'Science Fiction'],
    description: 'A future society driven by technology and pleasure.',
    metadata: { year: 1932, isbn: '9780060850524' },
  },
  {
    volumeId: 'vol-7',
    title: 'The Catcher in the Rye',
    authors: ['J.D. Salinger'],
    categories: ['Classic', 'Coming-of-Age'],
    description: 'Holden Caulfield’s journey through teenage alienation.',
    metadata: { year: 1951, isbn: '9780316769488' },
  },
  {
    volumeId: 'vol-8',
    title: 'The Hobbit',
    authors: ['J.R.R. Tolkien'],
    categories: ['Fantasy', 'Adventure'],
    description: 'Bilbo Baggins embarks on an epic quest for treasure.',
    metadata: { year: 1937, isbn: '9780547928227' },
  },
  {
    volumeId: 'vol-9',
    title: 'Fahrenheit 451',
    authors: ['Ray Bradbury'],
    categories: ['Dystopian', 'Science Fiction'],
    description: 'A future where books are outlawed and burned.',
    metadata: { year: 1953, isbn: '9781451673319' },
  },
  {
    volumeId: 'vol-10',
    title: 'War and Peace',
    authors: ['Leo Tolstoy'],
    categories: ['Historical', 'Classic'],
    description: 'A sweeping epic of love and war in Napoleonic Russia.',
    metadata: { year: 1869, isbn: '9780199232765' },
  },
  {
    volumeId: 'vol-11',
    title: 'Crime and Punishment',
    authors: ['Fyodor Dostoevsky'],
    categories: ['Classic', 'Psychological'],
    description: 'A young man’s moral dilemmas after committing murder.',
    metadata: { year: 1866, isbn: '9780140449136' },
  },
  {
    volumeId: 'vol-12',
    title: 'The Lord of the Rings',
    authors: ['J.R.R. Tolkien'],
    categories: ['Fantasy', 'Adventure'],
    description: 'The epic struggle for Middle-earth against the forces of darkness.',
    metadata: { year: 1954, isbn: '9780618640157' },
  },
  {
    volumeId: 'vol-13',
    title: 'Jane Eyre',
    authors: ['Charlotte Brontë'],
    categories: ['Romance', 'Classic'],
    description: 'A tale of resilience, love, and independence.',
    metadata: { year: 1847, isbn: '9780142437209' },
  },
  {
    volumeId: 'vol-14',
    title: 'The Odyssey',
    authors: ['Homer'],
    categories: ['Epic', 'Classic'],
    description: 'Odysseus’s perilous journey home from the Trojan War.',
    metadata: { year: -800, isbn: '9780140268867' },
  },
  {
    volumeId: 'vol-15',
    title: 'Frankenstein',
    authors: ['Mary Shelley'],
    categories: ['Science Fiction', 'Classic'],
    description: 'A scientist’s creation turns into a monster.',
    metadata: { year: 1818, isbn: '9780141439471' },
  },
  {
    volumeId: 'vol-16',
    title: 'Dracula',
    authors: ['Bram Stoker'],
    categories: ['Horror', 'Classic'],
    description: 'The original vampire tale of terror and seduction.',
    metadata: { year: 1897, isbn: '9780141439846' },
  },
  {
    volumeId: 'vol-17',
    title: 'Wuthering Heights',
    authors: ['Emily Brontë'],
    categories: ['Romance', 'Classic'],
    description: 'A dark tale of passion and revenge on the Yorkshire moors.',
    metadata: { year: 1847, isbn: '9780141439556' },
  },
  {
    volumeId: 'vol-18',
    title: 'The Divine Comedy',
    authors: ['Dante Alighieri'],
    categories: ['Epic', 'Classic'],
    description: 'Dante’s journey through Hell, Purgatory, and Paradise.',
    metadata: { year: 1320, isbn: '9780142437223' },
  },
  {
    volumeId: 'vol-19',
    title: 'The Brothers Karamazov',
    authors: ['Fyodor Dostoevsky'],
    categories: ['Classic', 'Philosophical'],
    description: 'A profound exploration of faith, doubt, and family conflict.',
    metadata: { year: 1880, isbn: '9780374528379' },
  },
  {
    volumeId: 'vol-20',
    title: 'Don Quixote',
    authors: ['Miguel de Cervantes'],
    categories: ['Adventure', 'Classic'],
    description: 'The comic misadventures of a would-be knight and his squire.',
    metadata: { year: 1605, isbn: '9780060934347' },
  },
];

async function ingestBooks() {
  for (const book of books) {
    const res = await fetch('http://localhost:3000/api/rag/ingest/book', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(book),
    });
    const result = await res.json();
    console.log(result);
  }
}

ingestBooks();
